baseurl = "http://www.example.com"
title = "æƒ³ç¡è¦ºçš„å·¥ç¨‹å¸«"
theme = "hugo-coder"
languagecode = "zh-tw"
defaultcontentlanguage = "zh-tw"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Mai"
  info = "ã€Œç‚ºç”šéº¼æƒ³ç¡è¦ºï¼Ÿã€å› ç‚ºæˆ‘ç†¬å¤œåšäº†é€™å€‹ Blog ğŸ’¤"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.png"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/fangmai001"
[[params.social]]
  name = "Medium"
  icon = "fa fa-medium fa-2x"
  weight = 3
  url = "https://medium.com/@fangmai"

# Menu links
[[menu.main]]
  name = "æŠ€è¡“"
  weight = 1
  url  = "tech/"
[[menu.main]]
  name = "ç”Ÿæ´»"
  weight = 2
  url = "life/"
